### ISSUE TITLE
OpenSSL 1.1.0 not supported 

### ISSUE THREAD

**Issue by ryuu1998** [RedDeadDepresso/BAAuto#14]
Script Initialisation Error
Traceback (most recent call last):
  File "C:\Users\msi_pc\Desktop\BAAuto-main\script.py", line 10, in <module>
    from modules.login import LoginModule
  File "C:\Users\msi_pc\Desktop\BAAuto-main\modules\login.py", line 1, in <module>
    from util.utils import Region, Utils
  File "C:\Users\msi_pc\Desktop\BAAuto-main\util\utils.py", line 11, in <module>
    from util.adb import Adb
  File "C:\Users\msi_pc\Desktop\BAAuto-main\util\adb.py", line 2, in <module>
    import uiautomator2 as u2
  File "C:\Users\msi_pc\AppData\Local\Programs\Python\Python37-32\lib\site-packages\uiautomator2\__init__.py", line 40, in <module>
    import adbutils
  File "C:\Users\msi_pc\AppData\Local\Programs\Python\Python37-32\lib\site-packages\adbutils\__init__.py", line 14, in <module>
    from ._device import AdbDevice, Sync
  File "C:\Users\msi_pc\AppData\Local\Programs\Python\Python37-32\lib\site-packages\adbutils\_device.py", line 32, in <module>
    import requests
  File "C:\Users\msi_pc\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\__init__.py", line 43, in <module>
    import urllib3
  File "C:\Users\msi_pc\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\__init__.py", line 42, in <module>
    "urllib3 v2.0 only supports OpenSSL 1.1.1+, currently "
ImportError: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'OpenSSL 1.1.0h  27 Mar 2018'. See: https://github.com/urllib3/urllib3/issues/2168

most of the solutions i found in the internet suggesting updating python to ver higher than 3.7 
i had python 3.9 to began with and most of the libraries in the requirement.txt did install until i downgraded python 
and now cant use it due to this error above  
I'm not expert in the major so i ask for some help

**Comment by RedDeadDepresso** [comment]
Hi, 
I am sorry I forgot to specify to download the latest version of python which is 3.12 on my README.md. Also, remember to add adb and python to PATH. Here are some detailed instructions if you need help.

 https://github.com/RedDeadDepresso/BAAuto/issues/7#issuecomment-1747275236

**Comment by ryuu1998** [comment]
Thanks 
Everything is working now

**Comment by RedDeadDepresso** [comment]
No problem, that's nice to hear. Also, I saw you star my MBA repository. Just to tell you, it's a fork, a copy on my account to experiment on. The original one is https://github.com/MaaAssistantArknights/MBA

**Comment by RedDeadDepresso** [comment]
Also, consider checking out [Perseus](https://github.com/RedDeadDepresso/Perseus) since you starred Alas. The easiest way to install it is using [Perseus CI](https://github.com/n0k0m3/PerseusCI). Follow the instructions in PerseusCI and then:

1. Download the xapk from [ApkPure](https://m.apkpure.com/azur-lane-apk/com.YoStarEN.AzurLane)
2. Rename the xapk into zip and then extract the obb file from Android\obb\com.YoStarEN.AzurLane
3. Paste the obb file into your emulator or phone in the directory \sdcard\Android\obb\com.YoStarEN.AzurLane
4. Run Azur Lane and download the game files
5. Settings can be found inside Perseus.ini, located within the game's external files directory (/sdcard/Android/data/{package-name}/files/).
If you're unsure of your region's package name, just look it up. All of them include "AzurLane" though.

Enabling the Skins mod gives you all skins in-game as if you had bought them. They are persistent between restarts.

**Comment by ryuu1998** [comment]
Thanks fir the recommendations
I’m already using both
The MBA is still way in the development 
There is another one called BAAS “ Blue Archive auto script “ which is quite similar to ALAS but unfortunately the global servers still under development too but way better and more active than MBA
